In [ ]:
� Sample Input & Output: 
�
� Sample Input (Generated Randomly) 
stock_prices = np.array([ 
[120, 340, 450, 220, 310], 
[330, 420, 380, 250, 410], 
[150, 280, 290, 230, 200], 
# ... (27 more rows) 
]) 
�
� Expected Output 
Average stock prices: [230.5  350.2  400.1  260.9  320.8] 
Highest price recorded: 480 at Day 14, Company 3 
Normalized prices: 
[[0.1   
[0.6   
0.7   
0.8   
0.85  0.3   0.6  ] 
0.72  0.35  0.75 ] 
... 
] 
Risky Investment Days: 
Day 1: [120, 150] 
Day 10: [180, 195]

In [9]:
import numpy as np
dataset=np.random.randint(100,500,(30,5))
print(dataset)

[[449 191 496 141 454]
 [282 260 137 186 217]
 [444 208 406 392 279]
 [493 289 149 106 120]
 [113 206 146 219 368]
 [367 413 305 423 160]
 [360 108 400 325 217]
 [288 138 492 357 354]
 [234 241 262 367 295]
 [218 200 128 427 369]
 [492 499 226 359 211]
 [238 332 237 189 370]
 [198 373 483 265 158]
 [393 275 252 491 406]
 [232 128 349 449 188]
 [474 101 176 111 326]
 [145 208 242 129 350]
 [467 473 282 448 427]
 [293 421 225 289 172]
 [485 463 268 212 422]
 [321 247 275 137 238]
 [130 462 489 153 187]
 [236 418 326 186 472]
 [457 165 328 279 313]
 [105 456 329 429 431]
 [464 132 358 490 349]
 [360 175 497 213 235]
 [495 287 374 448 188]
 [415 284 481 209 311]
 [227 196 498 205 276]]


In [14]:
Average_stock_prices=np.mean(dataset,axis=0) 
avg=[]
for i in Average_stock_prices:
    avg.append(round(i,1))
print(f"Average stock prices:",avg)
maxi = np.max(dataset)
index = np.argwhere(dataset==maxi)
print(index)
print(f"Highest price recorded: {maxi} at Day {index[0][0]+1}, Company {index[0][1]}")
norm = np.linalg.norm(dataset)
matrix = dataset/norm
print("Normalized Prices : ")
print(matrix)
print("Risky Investments Days:")
for i in range(len(dataset)):
    mask = dataset[i] <200
    if len(dataset[i][mask]) !=0:
        print(f"Day {i+1} : {dataset[i][mask]}")

Average stock prices: [329.2, 278.3, 320.5, 287.8, 295.4]
[[10  1]]
Highest price recorded: 499 at Day 11, Company 1
Normalized Prices : 
[[0.11279884 0.04798347 0.12460629 0.03542235 0.11405496]
 [0.07084471 0.06531782 0.03441746 0.04672736 0.05451525]
 [0.11154273 0.05225425 0.10199628 0.09847917 0.07009104]
 [0.12385263 0.07260326 0.03743213 0.02662957 0.03014668]
 [0.02838813 0.05175181 0.03667847 0.0550177  0.09244983]
 [0.09219861 0.10375484 0.07662282 0.10626706 0.04019558]
 [0.09044005 0.02713202 0.10048895 0.08164727 0.05451525]
 [0.07235204 0.03466869 0.12360141 0.08968639 0.08893272]
 [0.05878603 0.06054459 0.06582026 0.09219861 0.0741106 ]
 [0.05476648 0.05024447 0.03215646 0.10727195 0.09270105]
 [0.12360141 0.12535996 0.05677626 0.09018883 0.05300792]
 [0.05979092 0.08340583 0.0595397  0.04748103 0.09295228]
 [0.04974203 0.09370594 0.1213404  0.06657393 0.03969313]
 [0.09873039 0.06908615 0.06330804 0.12335018 0.10199628]
 [0.05828359 0.03215646 0.08767661 0.11279884 0.04

In [ ]:
�
� Challenge 2: The Space Mission Resource Allocation 💼 
⏳ Time: 30 minutes 
⏳ Concepts Covered: Array creation, sum, max, standard deviation, transposition 
�
� Scenario: 
NASA is preparing a Mars mission ⏳ and needs to efficiently allocate oxygen, water, and 
food for astronauts over 6 months. Your job as a space engineer is to analyze and optimize 
resource consumption! 
�
� Task: 
 Create a (6, 3) NumPy array, where: – – 
Rows (0-5) represent months. 
Columns (0-2) represent oxygen, water, and food consumption (in tons). 
Compute total resources required for the entire mission. 
Identify which resource had the highest consumption in any given month and in 
total. 
Compute the standard deviation of each resource to measure consistency in 
consumption. 
Transpose the matrix to display the resource-wise breakdown by month.

In [7]:
import numpy as np
rand=np.random.randint(1,20,(6,3))
print(rand)

[[ 1 18 11]
 [19  7  8]
 [16 16 16]
 [10  7 12]
 [ 7  9  6]
 [14 14 14]]


In [6]:
oxygen = np.sum(rand[:, 0])
water= np.sum(rand[:, 1])
food= np.sum(rand[:, 2])
print(f"Total resources needed(tons):Oxygen: {oxygen}, Water: {water}, Food: {food}")
print(f"Highest consumption in a month:")
max_values=np.max(rand,axis=0)
print(max_values)
max_months = np.argmax(rand, axis=0)+1 
print(max_months)
highest_resource_index = np.argmax([oxygen, water, food])
resource_names = ["Oxygen", "Water", "Food"]

print(f"Highest consumption in a month: {resource_names[np.argmax(max_values)]} ({max_values[np.argmax(max_values)]} tons in month {max_months[np.argmax(max_values)]})")
std_oxygen = round(np.std(rand[:, 0]), 1)
std_water = round(np.std(rand[:, 1]), 1)
std_food = round(np.std(rand[:, 2]),1)
print(f"Standard deviation of consumption: Oxygen: {std_oxygen}, Water: {std_water}, Food: {std_food}")
print("Transposed matrix:\n")
print(rand.T)

Total resources needed(tons):Oxygen: 39, Water: 60, Food: 47
Highest consumption in a month:
[11 17 15]
[4 2 1]
Highest consumption in a month: Water (17 tons in month 2)
Standard deviation of consumption: Oxygen: 3.9, Water: 4.4, Food: 5.1
Transposed matrix:

[[ 6  9  2 11 10  1]
 [11 17  6  6  6 14]
 [15  1  8 13  8  2]]


In [2]:
import numpy as np
dataset = np.random.randint(10,50,(5,10))
print(dataset)
avg = (np.sum(dataset,axis =1))/10
avg = [round(a,1) for a in avg]
print("Average points per game:")
print(avg)
sums = np.sum(dataset,axis=1)
print()
print(f"Best-performing player: Player {np.where(sums==max(sums))[0][0]} (Total: {max(sums)} points)")
print(f"Worst-performing player: Player {np.where(sums==min(sums))[0][0]} (Total: {min(sums)} points)")
print()
print("Games with scores above 30")
for i in range(len(dataset)):
    mask = dataset[i]>30
    if len(dataset[i][mask]) != 0:
        print(f"Player {i+1}: Games {dataset[i][mask]}")
print()
temp = {}
for i in range(len(sums)):
    temp[i+1] = sums[i]
print(temp)
di = dict(sorted(temp.items(), key=lambda item: item[1],reverse = True))
i =1
print("Sorted Players by Total Points")
for j in di.keys():
    print(f"{i}. Player {j} - {di[j]} points")
    i+=1

[[21 11 46 10 42 26 37 29 17 39]
 [28 17 30 47 17 19 18 21 13 14]
 [49 36 28 29 31 46 48 36 41 47]
 [34 20 33 28 31 16 31 19 49 26]
 [19 30 25 32 37 14 19 47 17 48]]
Average points per game:
[27.8, 22.4, 39.1, 28.7, 28.8]

Best-performing player: Player 2 (Total: 391 points)
Worst-performing player: Player 1 (Total: 224 points)

Games with scores above 30
Player 1: Games [46 42 37 39]
Player 2: Games [47]
Player 3: Games [49 36 31 46 48 36 41 47]
Player 4: Games [34 33 31 31 49]
Player 5: Games [32 37 47 48]

{1: 278, 2: 224, 3: 391, 4: 287, 5: 288}
Sorted Players by Total Points
1. Player 3 - 391 points
2. Player 5 - 288 points
3. Player 4 - 287 points
4. Player 1 - 278 points
5. Player 2 - 224 points
